### ISSUE TITLE
你没处理物理断网的情况。或者说客户端断电。。

### ISSUE THREAD

**Issue by hykych** [isayme/socks5#1]
如果很多客户端断电，那事件注册了又不释放，不是白白浪费。

**Comment by hykych** [comment]
如果要处理，有什么可行性方案

**Comment by isayme** [comment]
@hykych 抱歉, 写的时候理解不深, 后来很少写c, 所以一直没有进一步的改善. 有时间定会改善下.

**Comment by isayme** [comment]
@hykych 断电的话应该会收到read事件吧, 然后recv读返回不大于0, 这时候会释放资源的

**Comment by hykych** [comment]
ok，谢谢。应该是等到tcp默认超时才会收到read事件吧

**Comment by hykych** [comment]
@isayme ok，谢谢回答。应该是等到tcp默认超时才会收到read事件吧

**Comment by isayme** [comment]
恩, 我的理解是这样. 因为没有keepalive, 所以客户端断网或crash之类的都是超时才会触发吧.
