### ISSUE TITLE
make失败，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [isayme/socks5#2]
hi.

root@AR:~/socks5# ls
bin  inc  makefile  README.md  src
root@AR:~/socks5# ls bin
root@AR:~/socks5# make
gcc src/liblog/liblog.c -g -DLINUX -shared -fPIC -Iinc -o liblog.so
mv liblog.so bin/
gcc src/libdaemon/libdaemon.c -g -DLINUX -shared -fPIC -Iinc -o libdaemon.so
mv libdaemon.so bin/
gcc src/libthread/libthread.c -g -DLINUX -shared -fPIC -Iinc -o libthread.so
mv libthread.so bin/
gcc src/libconfig/libconfig.c -g -DLINUX -shared -fPIC -Iinc -o libconfig.so
mv libconfig.so bin/
gcc src/socks5/socks5.c -g -Wall -O3 -DLINUX -Iinc -Wl,-rpath,bin,-rpath, -Lbin -lpthread -llog -ldaemon -lconfig -lev -lthread -o socks5
src/socks5/socks5.c:19:16: fatal error: ev.h: 没有那个文件或目录
compilation terminated.
make: **\* [socks5] 错误 1
root@AR:~/socks5#

**Comment by isayme** [comment]
依赖libev库, 你需要安装下的.

**Comment by luckypoem** [comment]
hi.

安装了 libev，（apt-get install libev-dev),成功启动了./bin/socks5 -p 2233 -d y,不过没过多久（不到2分钟），这个socks5进程就退出了。怎么回事呢？

**Comment by isayme** [comment]
@luckypoem 抱歉, 这个是很久之前的玩具, 稳定性不是当时的重点. 后面有时间我要深入理解下libev, 再考虑优化下代码.

**Comment by isayme** [comment]
@luckypoem 你说的退出是crash了还是其他原因? 有log看看吗?

**Comment by luckypoem** [comment]
hi.

在哪里看log文件？

**Comment by isayme** [comment]
可执行文件所在的目录会有日志. 如果crash的话可能还会有crash产生的文件以辅助定位问题.

**Comment by luckypoem** [comment]
现在它不崩溃了。可能是这两天你改了代码的原因。不过把它用作公共的 http
proxy,还是不行。（我是指在浏览器里设置http代理为my-vps-ip:2233,我是想把它用作tor的前置代理。

root@ar2:~/socks5-proxy/bin# ps aux|grep socks5[21:33:28 2016-01-11]
[ERROR] {src/socks5/socks5.c:261} go to error [0].

[21:33:28 2016-01-11] [ERROR] {src/socks5/socks5.c:384} auth error.

root      5839  0.0  0.1  19288   948 ?        Ss   21:22   0:00 ./socks5
-p 2233 -d y

root      5849  0.0  0.1   7832   840 pts/0    S+   21:33   0:00 grep socks5

root@ar2:~/socks5-proxy/bin#

root@ar2:~/socks5-proxy/bin# ps aux|grep socks5

root      5839  0.0  0.1  19288   948 ?        Ss   21:22   0:00 ./socks5
-p 2233 -d y

root      5851  0.0  0.1   7832   840 pts/0    S+   21:34   0:00 grep socks5

root@ar2:~/socks5-proxy/bin# ps aux|grep socks5

root      5839  0.0  0.1  19288   948 ?        Ss   21:22   0:00 ./socks5
-p 2233 -d y

root      5853  0.0  0.1   7832   840 pts/0    S+   21:35   0:00 grep socks5

root@ar2:~/socks5-proxy/bin# ls

liblog.so  socks5  socks5-2016-01-11-21-19.log socks5-2016-01-11-21-22.log

root@ar2:~/socks5-proxy/bin#

root@ar2:~/socks5-proxy/bin# ps aux|grep socks5

root      5839  0.0  0.1  19288   948 ?        Ss   21:22   0:00 ./socks5
-p 2233 -d y

root      5858  0.0  0.1   7832   844 pts/0    S+   21:41   0:00 grep socks5

root@ar2:~/socks5-proxy/bin#

2016-01-12 10:19 GMT+08:00 iSayme notifications@github.com:

**Comment by isayme** [comment]
这两天主要是删了一些无用的代码. 
目前这是一个简单的socks5实现, 如果放在vps上运行, 是可以直接设置浏览器socks5代理到你的服务器的.

不过目前的实现还有效率问题, 不建议作为你主要的代理使用.

**Comment by luckypoem** [comment]
不过现在又退出了。
root@ar2:~# ps aux|grep socks5
root      7495  0.0  0.1   7832   840 pts/0    R+   01:30   0:00 grep socks5
root@ar2:~#

**Comment by isayme** [comment]
这个退出的问题我今天晚上查看看吧

**Comment by isayme** [comment]
@luckypoem 退出问题目前我还没遇到. 
你是不是通过国内的IP直接连接你vps服务的? 如果是的话就可能是墙的原因.

**Comment by luckypoem** [comment]
是的，我是通过国内的IP直接连接我的vps服务器，不过这跟墙有什么关系？我的vps的ip又没被封。

**Comment by isayme** [comment]
墙能够识别出socks5协议的连接, 然后会冒充你向vps发close包, 也会向你本机发close包...

**Comment by luckypoem** [comment]
hi.

用你这个socks5作为tor的前置代理成功的连上了tor网络，进行翻墙。翻了3个小时，翻墙失败，发现socks5进程又退出了。看样子真是受到了gfw的干扰。不过我用这个程序http://sourceforge.net/projects/ssocks/所搭建的socks proxy进程却一直在运行中，它有用户认证机制，我启用了用户认证。估计是启用了用户认证的socks proxy不会受到gfw的干扰？你可否替这个程序添加用户认证机制吗

**Comment by isayme** [comment]
可以的加的. 如果你会用node, 可以看我这个[socks5-server](https://github.com/isayme/socks5-server), 这个里面已经支持用户名密码验证.

crash的问题我猜测是墙给我的包不按套路, 我这边没检测导致的, 我可以修复.

另外, 用户验证机制应该不足以阻挡得住墙,,,

**Comment by luckypoem** [comment]
hi.

我用mocks-  http://sourceforge.net/projects/mocks/这个socks proxy app无任何问题。它在我的vps上一直未退出（好几天了），用它作为tor的前置代理，我成功的连上了tor网络进行翻墙。怎么它就不受gfw的干扰呢？所以我觉得还是你的这个程序有点不稳定。你的这个程序我只好配合suporvisor来使用。
