### ISSUE TITLE
Asynchronous socks auth / handshake

### ISSUE THREAD

**Issue by vavrecan** [isayme/socks5#3]
first of all, great job - I have feeling that there was no other simple socks5 server using libev. 

I see there are few issues with socks5_auth method, because it is synchronous and sometimes recv or send return -1 because they need more time. It could be resolved by doing proxy authentication also using libev asynchronously - I implemented it in in socks client version already: https://github.com/vavrecan/sniproxy/blob/master/src/connection.c#L216

**Comment by isayme** [comment]
closed, more detail see branch `v2`
