### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by vavrecan** [isayme/socks5#8]
how does the connection get closed - is there any timeout?
when doing a lot of requests

```
for i in `seq 1 50000`;
do
	curl -v -x socks5h://127.0.0.1:1080 http://127.0.0.1:8080 &
done    
```

the socks5_conn_close does not seems to be called and the memory grows with more requests.

**Comment by vavrecan** [comment]
forget everything i wrote. I think there is a memory leak. On the connection something allocates 1152b buffer but did not figure out where it comes from yet ^^

**Comment by vavrecan** [comment]
found it - https://github.com/isayme/socks5/pull/9/commits/db1b781fba9d172c9a4787f92c0de15e47f49fec
the conn allocated at socks5_conn_new was never freed

**Comment by isayme** [comment]
🍻
